name = "client-flow-360-crm"
compatibility_date = "2024-08-27"
pages_build_output_dir = "./"

[env.production]
name = "client-flow-360-crm"

[env.preview]
name = "client-flow-360-crm-preview"

# Custom domain settings (can be configured in Cloudflare dashboard)
# [env.production.custom_domain]
# domain = "clientflow360.com"