name = "client-flow-360-crm"
compatibility_date = "2024-08-26"
account_id = ""

[env.production]
name = "client-flow-360-crm"
compatibility_date = "2024-08-26"

[[env.production.routes]]
pattern = "client-flow-360.pages.dev"
zone_name = "pages.dev"

[build]
command = "echo 'Using pre-built files'"
publish = "production-build"